DROP TABLE visits;
DROP TABLE city;
DROP TABLE country;

CREATE TABLE country(
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE city(
  ID SERIAL8 PRIMARY KEY,
  name VARCHAR(255),
  country_id INT4 REFERENCES country(id) ON DELETE CASCADE
);

CREATE TABLE visits(
  ID SERIAL8 PRIMARY KEY,
  CITY_ID INT4 REFERENCES city(id) ON DELETE CASCADE,
  visited BOOLEAN
);
